extends: eslint-config-dmitmel/presets/node
env:
  browser: true

rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules

overrides:
  - files: '**/*.ts'
    extends:
      # - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
      - eslint-config-dmitmel/presets/typescript-addon
    parserOptions:
      project: 'tsconfig.json'
