extends: eslint-config-dmitmel/presets/node
env:
  browser: true
parserOptions:
  sourceType: module

rules:
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: functions
      allow:
        - name
        - length
        - location
        - self
        - status
        - event
        - onload

  func-names: off

  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules

  node/no-unpublished-import: off

overrides:
  - files:
      - '**/*.ts'
    extends:
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'

    parserOptions:
      project: 'tsconfig.json'

    rules:
      prefer-const: off

      # copied from camelcase
      '@typescript-eslint/camelcase':
        - warn
        - allow:
            - '^NWJS_Helpers$'

      # copied from no-unused-vars
      '@typescript-eslint/no-unused-vars':
        - warn
        - vars: all
          varsIgnorePattern: '^_'
          args: all
          argsIgnorePattern: '^_'
          ignoreRestSiblings: true
          caughtErrors: all
          caughtErrorsIgnorePattern: '^_'

      # copied from no-use-before-define
      '@typescript-eslint/no-use-before-define':
        - error
        - functions: false
          classes: false
          enums: false
          variables: true
          typedefs: false # maybe?

      # @typescript-eslint/no-useless-constructor is used instead
      no-useless-constructor: off

      # because I have to use '.js' file extensions in imports
      node/no-missing-import: off

      '@typescript-eslint/no-non-null-assertion': off

      '@typescript-eslint/unbound-method': off

      '@typescript-eslint/explicit-function-return-type':
        - warn
        - allowExpressions: true
          allowTypedFunctionExpressions: true
          allowHigherOrderFunctions: true

      '@typescript-eslint/no-empty-interface': off

      '@typescript-eslint/triple-slash-reference': off
