extends: eslint-config-dmitmel/presets/node
env:
  browser: true

rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules

overrides:
  - files: '**/*.ts'
    extends:
      # - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
      - eslint-config-dmitmel/presets/typescript-addon
    parserOptions:
      project: 'tsconfig.json'

  - files: '**/*.d.ts'
    rules:
      # `declare var` implicitly creates a property on the `Window` object
      no-var: off
      no-shadow: off
      '@typescript-eslint/no-empty-interface': off
      '@typescript-eslint/no-explicit-any':
        - warn
        - ignoreRestArgs: true

      # everything in declarations is public anyway
      '@typescript-eslint/explicit-member-accessibility': off

      # triggers on weird edge-cases such as `import export a = b`
      '@typescript-eslint/no-use-before-define': off
