name: CI
on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout this repo
        uses: actions/checkout@v2

      - name: install node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: get Yarn cache dir
        id: yarn_cache_dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: setup Yarn cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn_cache_dir.outputs.dir }}
          key: |
            r1/${{ github.workflow }}/${{ runner.os }}/yarn/${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            r1/${{ github.workflow }}/${{ runner.os }}/yarn/

      - run: yarn install --frozen-lockfile
      - run: yarn run check
      - run: yarn run lint
      - run: yarn run check-fmt
